version: '3.7'
services:

  #PHP Service
  app:
    image: laradock/php-fpm:latest-7.4
    container_name: app
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www

    ports:
      - 8080:80
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: finjet
      MYSQL_ROOT_PASSWORD: finjet
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3600:3600
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge